---
title: "FAQ"
editor: visual
---

## **What is FoolsFest?**

It’s a festive co-created campout. Think of it like a DIY festival.  Just US doin’ our thing and making silly, foolish magic!  

## **What is provided at FoolsFest?**

**Camping space:** A campsite where you can pitch a tent, hang a hammock, or park a vehicle to sleep in under the shade of beautiful California live oak trees! There are potable water spigots throughout Live Oak Campground and plenty of space, so feel free to spread out and build up. There will be “greeters” or at least folks in the know at the Pavillion to help you find a spot and orient you to the campground when you arrive. 

**Restrooms:** The campground’s bathrooms are within a few minutes’ walk from your campsite, with running water, flush toilets, sinks, and showers. The showers are communal style, separated by genders - think gym locker room vibes, with many shower heads in one big open room.

**Kitchen:** An industrial kitchen is on-site, with a walk-in fridge, sinks, stoves, and greywater disposal. The industrial kitchen will primarily be available for those preparing food and beverage-related contributions for FoolsFest (see below), so please plan to store and prepare all personal food at your campsite, using your own cooking gear. **There are no fires allowed at Live Oak , except for in the fire ring** by the kitchen; feel free to roast your weenies there.

**Electricity:** There are outlets at all the buildings at Live Oak, but that's about it. If you want power outside of common spaces, we recommend bringing portable battery packs. **Extension cords are technically not allowed at Live Oak.**

**Food:** The plan for now is for everyone to be self-sufficient for food. Don't forget to bring your own plates, bowls, cups, utensils, etc.

## **What do I need to provide?**

Whatever you need to meet your own basic needs that isn’t provided above! The two big things to bring are your personal meals and your shelter (tents, hammocks, camper vans, etc.). Other helpful items to put on your packing list: a headlamp, a silly hat, a yoga mat, first aid kit, earplugs, sunscreen, shower sandals, towel, a portable chair, warm layers, and your sense of foolish fun!

## **Will there be a central trash/recycling or do we take out waste with us?**

This is still a **Pack it in / Pack it out** event — our motto is *leave it better than we found it!* While the venue operators are providing a trash trailer, **trash cans will only be located at the pavilion**. That means you need to wrangle your trash at your campsite or elsewhere on the grounds to make sure your waste ends up in a proper receptacle.

Help us keep the space clean and our footprint small by bringing **reusable** cups, utensils, plates, and cloth napkins. Also, bring your **reusable water bottles** — potable water is available onsite, so no need for single-use plastic.

## **How much do tickets cost?**

We are not selling tickets for FoolsFest.  If you would like to contribute financially toward the shared costs of hosting the event we would greatly appreciate it. The suggested donation range per person is \$135 – \$235 to cover the shared costs such as the venue rental, insurance, operations, food and other supplies, but we of course are grateful for any amount.If we end up in the black, any additional funds will be used for FoolsFests to come, such as to secure a venue for next year.  

Please donate via Venmo, cash, or check. To donate via Venmo please send to \@Matthew-Robbins-16 and include FoolsFest2026 and the name of those you are donating on behalf of in the notes. To donate via cash or check you can either give to us in person or send to Matthew Robbins 930 Cieneguitas Road Santa Barbara, CA 93110.

## **When and where should we plan to arrive? And is it possible to come just for the day or do I have to stay overnight?**

We have the entire campground rented out from Thursday, April 30 - Sunday, May 3. All are welcome to come and go whenever they please. Thursday is the setup day and if you’d like to come then to help out, please let Erin or Mateo know (or just show up)! On Sunday we’ll do an all-hands-on-deck cleanup, so please plan to help clean up before leaving.

There’s no requirement to stay overnight, though many thrills, skills, and frills will only be revealed after dark ;) If you would prefer other accommodations, Santa Barbara and Santa Ynez are each about a 20-30 minute drive away.   

## **How can I contribute to FoolsFest?**

There are many ways to contribute to FoolsFest! As a DIY co-created campout, this event is a blank canvas for you to fill in with your preferred color of paint (or painted body part). There are three primary ways to contribute:

**1) Share your passion!** FoolsFest is a co-created experience, made entirely by us fools! If you’re someone who has a skill or passion you’d like to share, we’d love to hear about it. You could play music, dance, share a skill, lead a movement class, do some art, give a talk, put on a workshop, prepare food or drink to share, plan a game, and so much more - the sky’s the limit! Any and all forms of silliness and creativity are encouraged. 

**2) Volunteer!** FoolsFest is only happening because YOU will help make it happen. We’ll be gathering interest in specific volunteering duties, but we’re counting on you to pitch in when you see something that needs to be done. Is there trash on the ground? Pick it up. See someone struggling to put up a tent? Pitch in and give them a hand. Someone cooked you dinner? Clean the dishes!

**3) Participate!** Ultimately, this event is about showing up and just being present :) Enjoy and appreciate our time together, and the things other people are bringing! Get to know your fellow fools! Lend a hand! Tell a joke! Accept a gift! Learn a skill! Dance a jig! Explore Live Oak! Wear a costume! Participation can mean so many things, whether quiet or expressive, both behind-the-scenes and out front. We’re so excited to get foolish together!

## **I am interested in sharing food or drink at FoolsFest, do I have to prepare enough for all attendees?**

No, you don’t have to bring enough for everyone, just aim for an amount that feels doable to you. People and events will be spread out around the campground, so it will be rare that all participants will be doing the same thing at the same time. Everyone should plan to take care of their own needs. Let us know if you are planning to use the communal kitchen for a food contribution at any point so we can coordinate with any other food plans.

## **Do I have to share my contribution at my campsite?**

You are welcome to share your contribution at your campsite, or in any common spaces! An industrial kitchen will be available for food and beverage-related contributions open to the FoolsFest community, a Public House will be available for events: skillshares, workshops, tavern takeovers or any other event-like contributions, and stages will be available for dance, performance, or music-related contributions. There is also a TON of open, free space throughout the campground - be creative, and use whatever space you’d like!

Reach out to Mateo or Erin to let us know what type of contribution you’ll be providing, and where you’d ideally like to set it up.  Spur-of-the-moment contributions are also welcomed and there will be a central message board where you can post last minute additions to FoolsFest.

## **Is there a dress code?**

Dress to express! Consider bringing fun, funny, unique costume pieces that make you feel great and may delight your fellow fools. We celebrate bodies of all forms, sizes, shapes, and functions. Bring whatever you'll need to stay comfortable in the Great Outdoors - closed-toed shoes and layers aren't a bad idea!

## **Should I be concerned about wildlife at Live Oak Campground?**

No, though please make sure not to leave any food accessible in your campsite to avoid critters!

## **Are pets allowed?**

There are no pets allowed at FoolsFest.  

Please reach out to us if there are special circumstances that make leaving your furry buddy at home a hardship.

## **Are kids allowed?**

Yes! Kids are enthusiastically welcome at FoolsFest. We hope to collectively create kid-friendly spaces (“Kidsville!”), activities, and contributions throughout the weekend. Let us know if you have ideas! However, just like any trip with kids, FoolsFest with kids may take some extra preparation, planning, and diligence. For instance, there may be suggestive or mature themes present during the festival, depending on the music, events, performances, and other contributions offered.  

## **What's the photo and video policy for FoolsFest?**

To maintain an atmosphere where everyone feels comfortable expressing themselves freely and without worry, you must obtain clear and informed consent from anyone you are photographing before doing so. In addition, you must obtain clear and informed consent from those captured before posting any photos or videos on social media.
